### ISSUE TITLE
Drop i686 repository

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/OpenMandrivaAssociation.github.io#47]
Drop i686 repository for good and do not ship 32 bit ISO at all.

Build dual arch packages for example:
libx11:
- lib64x11_6
- libx11_6
from one libx11.spec file
We may build 32 bit packages into x86_64(znver1/other) repo to suffice Steam and other closed source software.
Same thing does ClearLinux.

**Comment by abucodonosor** [comment]
I do that for a long time in Frugalware. We cross build 32bit bit libs. Depending on
what you want to support there are around 200 packages you need cross compile.

**Comment by tpgxyz** [comment]
In progress, but qute close to done

**Comment by AngryPenguinPL** [comment]
> In progress, but qute close to done

As far as I know:
We haven't been building ISO i686 for a long time.
The i686 repository is currently deprecated.
It is still active but not recommended for use, only as an emergency for applications that do not run in the x86_64 repo or have not yet been built as compact 32bit on the x86_64 branch. Eg some emulators.

For common things like Steam, WINE, @berolinux  built corresponding 32-libraries in the x86_64 repo. So for these purposes the i686 repo is no longer needed.

Currently, we can look for packages that still don't build properly or don't run on x86_64, or require i686 libraries to run. We need to make a list of them so that bero or someone else can move them to x86_64 as compact 32 or etc. to get rid of this repo completely.

**Comment by tpgxyz** [comment]
This is completed from 4.2 release.
